global:
  scrape_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'weather'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.18.0.11:8080', 'localhost:8080']
